name: 'Allure Report with History'
description: 'Generates and publishes Allure reports with history support'
author: 'velychkod'
runs:
  using: 'node16'
  main: 'dist/index.js'

inputs:
  allure-results-source:
    description: 'Path to the folder containing Allure results'
    required: true
  published-reports-branch:
    description: 'Branch where reports are published'
    required: true
  reports-to-keep:
    description: 'Number of old reports to keep'
    default: '20'
  generate-index-html-with-reports-history:
    description: 'Whether to generate index.html file with report history'
    default: 'true'
  gh-pages-url:
    description: 'GitHub Pages URL to access the reports'
    required: false
