name: "Allure Report with History"
description: "Generate Allure reports with history and deploy to GitHub Pages"
author: "Your Name <you@example.com>"
branding:
  icon: "graph"
  color: "blue"
runs:
  using: "node16"
  main: "dist/index.js"
inputs:
  allure-results-source:
    description: "Path to the Allure results directory"
    required: true
  published-reports-branch:
    description: "Branch where Allure reports will be published"
    required: true
  reports-to-keep:
    description: "How many historical reports to keep"
    required: false
    default: "20"
  generate-index-html-with-reports-history:
    description: "Generate an index.html with links to historical reports"
    required: false
    default: "true"
  gh-pages-url:
    description: "GitHub Pages URL to link the reports"
    required: false
