name: 'Allure Report with History'
description: 'Generates Allure report with historical results'
author: "velychkod"
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  allure-results-source:
    description: 'Path to Allure results'
    required: true
  published-reports-branch:
    description: 'Branch to push Allure report'
    required: true
  reports-to-keep:
    description: 'Number of historical reports to keep'
    required: false
    default: '20'
  generate-index-html-with-reports-history:
    description: 'Generate index.html with report history'
    required: false
    default: 'true'
  gh-pages-url:
    description: 'Optional URL to GitHub Pages for linking latest report'
    required: false
