name: "Allure Report Publisher with History (GH Pages)"
description: "Generates and deploys Allure reports to a specified branch while preserving history of previous reports."
author: "velychkod"

branding:
  icon: "bar-chart"
  color: "purple"

runs:
  using: "node16"
  main: "dist/index.js"

inputs:
  allure-results-path:
    description: "Path to the Allure results folder"
    required: true

  deploy-branch:
    description: "Branch where Allure reports should be published (e.g., gh-pages)"
    required: true

  reports-to-keep:
    description: "How many previous reports to keep in history"
    required: false
    default: "20"

  gen-index:
    description: "Generate index.html with links to previous reports"
    required: false
    default: "true"

  gh-pages-url:
    description: "Base URL where reports are hosted (used for summary link generation)"
    required: false

  git-user-name:
    description: "Git user name used for commit history"
    required: false
    default: "github-actions"

  git-user-email:
    description: "Git email used for commit history"
    required: false
    default: "actions@github.com"

  report-name:
    description: "Optional custom name for the generated report"
    required: false
